# Build settings
markdown: kramdown

collections:
  tables:
    output: true
  application_areas:
    output: true
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin

emptyarray: []

title: UH Documentation

baseurl: /uh-documentation