# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

commands:
  setup-env:
    description: "Sets up all dependencies"
    steps:      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install graphviz
          command: sudo apt-get install graphviz

      - run:
          name: install java for plantuml
          command: sudo apt-get install openjdk-8-jre-headless

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: create google config file
          command: echo $GOOGLE_CONFIG > config.json
jobs:
  build-test-deploy:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup-env
      - run:
          name: build site
          command: bundle exec jekyll build
      - run:
          name: run tests
          command: ./bin/test
      - setup-env
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: sync_to_s3
          command: |
            rm -rf _site && \
            bundle exec jekyll build && \
            aws s3 sync --delete _site/ s3://hackney-housing-needs-as-is
            
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-test-deploy
