# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

commands:
  setup-env:
    description: "Sets up all dependencies"
    steps:      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install graphviz
          command: sudo apt-get install graphviz

      - run:
          name: install java for plantuml
          command: sudo apt-get install openjdk-8-jre-headless

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle --without development

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  build-test-deploy:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup-env
      - run:
          name: build site
          command: bundle exec jekyll build
      - run:
          name: run tests
          command: ./bin/test
      - run:
          name: deploy
          command: ./bin/deploy

            
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-test-deploy
